### PR TITLE
Ansible version

### PR DESCRIPTION
**Pull request by k8soneill**
Setting ansible version at 2.6 in the slave image so the loop clauses in our pre-heat deployment ansible setup work in the pipeline environment.

### CODE REVIEW

**Review by gellner — APPROVED** [review]
LGTM if that's what you need to do

**Comment by andrew-garner** [comment]
If it's not too late, could we bump ansible to higher than 2.6? Ansible only support the current and two older minor versions, so 2.6 is already unsupported. https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#release-status

**Comment by k8soneill** [comment]
@andrew-garner It's not too late I'll bump it up to 2.9 and make sure it works

**Comment by andrew-garner** [comment]
Thanks :) Ansible also remove unsupported versions from the version picker on docs.ansible.com so it's hard to find the documentation for older versions too.

**Comment by andrew-garner** [comment]
If it passes your testing it's good for me.

**Review by andrew-garner — APPROVED** [review]

**Pull request merged**
